services:
  mongodb:
    image: mongo:latest
    container_name: mixir-dev-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mixir
    volumes:
      - mongodb_data:/data/db
      - ./script/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
    restart: always

volumes:
  mongodb_data:
    name: mixir-dev-mongodb-data