services:
  mongodb:
    image: mongo:latest
    container_name: mixir-dev-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: mixir
    ports:
      - 27017:27017
    volumes:
      - mongodb_data:/data/db
      - ./script/mongodb/init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro

  mongo-express:
    image: mongo-express:latest
    container_name: spark-dev-mongo-express
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://root:password@mongodb:27017/
      ME_CONFIG_BASICAUTH: false
    ports:
      - 8081:8081

volumes:
  mongodb_data:
    name: mixir-dev-mongodb-data